/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* ── M3 Dynamic Theme Colors (auto light/dark via CSS variables) ── */
        m3: {
          primary:                  'var(--md-sys-color-primary)',
          'on-primary':             'var(--md-sys-color-on-primary)',
          'primary-container':      'var(--md-sys-color-primary-container)',
          'on-primary-container':   'var(--md-sys-color-on-primary-container)',
          secondary:                'var(--md-sys-color-secondary)',
          'on-secondary':           'var(--md-sys-color-on-secondary)',
          'secondary-container':    'var(--md-sys-color-secondary-container)',
          'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
          surface:                  'var(--md-sys-color-surface)',
          'surface-dim':            'var(--md-sys-color-surface-dim)',
          'surface-bright':         'var(--md-sys-color-surface-bright)',
          'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
          'surface-container-low':  'var(--md-sys-color-surface-container-low)',
          'surface-container':      'var(--md-sys-color-surface-container)',
          'surface-container-high': 'var(--md-sys-color-surface-container-high)',
          'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
          'on-surface':             'var(--md-sys-color-on-surface)',
          'on-surface-variant':     'var(--md-sys-color-on-surface-variant)',
          outline:                  'var(--md-sys-color-outline)',
          'outline-variant':        'var(--md-sys-color-outline-variant)',
          error:                    'var(--md-sys-color-error)',
          'on-error':               'var(--md-sys-color-on-error)',
          'error-container':        'var(--md-sys-color-error-container)',
          'on-error-container':     'var(--md-sys-color-on-error-container)',
          background:               'var(--md-sys-color-background)',
          'on-background':          'var(--md-sys-color-on-background)',
        },
        /* ── M3 Static Light Palette (explicit hex from design.md §1.1) ── */
        'm3-light': {
          primary: '#0b57d0',
          'on-primary': '#ffffff',
          'primary-container': '#d3e3fd',
          'on-primary-container': '#041e49',
          secondary: '#00639b',
          'on-secondary': '#ffffff',
          'secondary-container': '#c2e7ff',
          'on-secondary-container': '#001d35',
          surface: '#f8fafd',
          'surface-dim': '#d9dadc',
          'surface-bright': '#f8fafd',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f0f4f9',
          'surface-container': '#edf2f7',
          'surface-container-high': '#e7ebf0',
          'surface-container-highest': '#e1e3e8',
          'on-surface': '#1f1f1f',
          'on-surface-variant': '#444746',
          outline: '#747775',
          'outline-variant': '#c4c7c5',
          error: '#b3261e',
          'on-error': '#ffffff',
          'error-container': '#f9dedc',
          'on-error-container': '#410e0b',
        },
        /* ── M3 Static Dark Palette (explicit hex from design.md §1.2) ── */
        'm3-dark': {
          primary: '#a8c7fa',
          'on-primary': '#062e6f',
          'primary-container': '#0842a0',
          'on-primary-container': '#d3e3fd',
          secondary: '#7fcfff',
          'on-secondary': '#003355',
          'secondary-container': '#004a77',
          'on-secondary-container': '#c2e7ff',
          surface: '#131314',
          'surface-dim': '#111213',
          'surface-bright': '#37393b',
          'surface-container-lowest': '#0e0e0f',
          'surface-container-low': '#1b1b1c',
          'surface-container': '#1e1f20',
          'surface-container-high': '#28292a',
          'surface-container-highest': '#333537',
          'on-surface': '#e3e3e3',
          'on-surface-variant': '#c4c7c5',
          outline: '#8e918f',
          'outline-variant': '#444746',
          error: '#f2b8b5',
          'on-error': '#601410',
          'error-container': '#8c1d18',
          'on-error-container': '#f9dedc',
        },
        /* ── Legacy Backward Compatibility (retained from old config) ── */
        google: {
          surface: "#f8fafd",
          surfaceDark: "#131314",
          card: "#ffffff",
          cardDark: "#1e1f20",
          tonal: "#f0f4f9",
          tonalDark: "#28292a",
          tonalHover: "#e9eef6",
          tonalHoverDark: "#333537",
          blue: "#0b57d0",
          blueHover: "#0842a0",
          bluePill: "#c2e7ff",
          bluePillDark: "#004a77",
          bluePillText: "#001d35",
          bluePillTextDark: "#c2e7ff",
          yellowPill: "#feefc3",
          yellowPillText: "#3c4043",
          textMain: "#1f1f1f",
          textMainDark: "#e3e3e3",
          textSub: "#444746",
          textSubDark: "#c4c7c5",
        },
      },
      fontFamily: {
        sans: ['Roboto', 'Outfit', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        display: ['Outfit', '-apple-system', 'sans-serif'],
        body: ['Roboto', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        /* ── M3 Typography Scale (design.md §2) ── */
        'display-lg': ['57px', { lineHeight: '64px', fontWeight: '400', letterSpacing: '-0.25px' }],
        'display-md': ['45px', { lineHeight: '52px', fontWeight: '400', letterSpacing: '0px' }],
        'display-sm': ['36px', { lineHeight: '44px', fontWeight: '400', letterSpacing: '0px' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '400', letterSpacing: '0px' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '400', letterSpacing: '0px' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '400', letterSpacing: '0px' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '400', letterSpacing: '0px' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '500', letterSpacing: '0.15px' }],
        'title-sm': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.1px' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400', letterSpacing: '0.5px' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400', letterSpacing: '0.25px' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400', letterSpacing: '0.4px' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '500', letterSpacing: '0.1px' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.5px' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.5px' }],
      },
      borderRadius: {
        /* ── M3 Shape Tokens (design.md §3) ── */
        'xs':   '4px',
        'sm':   '8px',
        'md':   '12px',
        'lg':   '16px',
        '2xl':  '16px',
        '3xl':  '28px',
        'full': '9999px',
      },
      boxShadow: {
        /* ── M3 Diffused Elevation Shadows (dynamic via CSS variables) ── */
        'm3-elevation-0': 'var(--md-sys-elevation-0)',
        'm3-elevation-1': 'var(--md-sys-elevation-1)',
        'm3-elevation-2': 'var(--md-sys-elevation-2)',
        'm3-elevation-3': 'var(--md-sys-elevation-3)',
        'm3-elevation-4': 'var(--md-sys-elevation-4)',
        'm3-elevation-5': 'var(--md-sys-elevation-5)',
      },
    },
  },
  plugins: [],
};
